--- # deploy a single ec2 instance running RHEL and Apache
- hosts: localhost
  gather_facts: true
  connection: local
    
  tasks:
    - name: Create webserver ec2 instances
      ec2:
        key_name: webserver_test
        region: us-east-1 
        instance_type: t2.micro 
        image: ami-2051294a 
        group_id: sg-39be1242
        wait: yes
        wait_timeout: 500
        instance_tags:
          Name: webserver 
          Env: sharedservices
        vpc_subnet_id: subnet-580e6072
        ebs_volumesize: 40
        assign_public_ip: no
